version: "3"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: facilita
      POSTGRES_PASSWORD: facilitapassword
